jobs:
- job: Build_Python
  timeoutInMinutes: 90
  pool:
    name: Azure Pipelines
    vmImage: $(VmImage)
  steps:
  - checkout: self
    submodules: true

  - bash: | 
      ./configure --enable-loadable-sqlite-extensions --enable-optimizations --with-openssl=$(brew --prefix openssl) `
      LDFLAGS="-L<path-to-sqlite>" \ `
      CPPFLAGS="-I<path-to-sqlite>" \ `
      make -j2

  - task: PowerShell@2
    displayName: 'Build Python $(VERSION)'
    inputs:
      targetType: filePath
      filePath: './builders/build-python.ps1'
      arguments: '-Version $(VERSION) -Platform $(Platform) -Architecture $(Architecture)'
      pwsh: true

  - task: PublishPipelineArtifact@1
    displayName: 'Publish Artifact: Python $(VERSION)'
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)' 
      artifactName: 'python-$(VERSION)-$(Platform)-$(Architecture)'